name: release

on: 
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags:
            - ${{ github.repository }}:${{ github.ref }}
            - ${{ github.repository }}:latest
            - ghcr.io/${{ github.repository }}:${{ github.ref }}
            - ghcr.io/${{ github.repository }}:latest
            - docker.pkg.github.com/${{ github.repository }}:${{ github.ref }}
            - docker.pkg.github.com/${{ github.repository }}:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7