name: release

on: 
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Get all docker tags
        uses: actions/github-script@v6
        id: tags
        with:
          script: |
            const ref = context.payload.ref.replace(/\/?refs\/tags\//, '')
            const tags = [
              'xbmlz/on-my-env:latest',
              `xbmlz/on-my-env:${ref}`,
              'ghcr.io/xbmlz/on-my-env:latest',
              `ghcr.io/xbmlz/on-my-env:${ref}`
            ]
            return tags.join(',')
          result-encoding: string

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{steps.tags.outputs.result}}
          cache-from: type=gha
          cache-to: type=gha,mode=max